#
# Copyright (c) 2025-2026, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""``pipecat init`` — the single starting point for building a Pipecat app.

``pipecat init`` initializes a new Pipecat project, then routes you to a build method:

- ``AGENTS.md`` — the coding-agent guide (read natively by most coding agents).
- ``CLAUDE.md`` — a one-line ``@AGENTS.md`` import so Claude Code loads it too.
- ``GETTING_STARTED.md`` — for the *developer*: how to drive the agent well
  (MCP setup, how to write the first prompt, what to expect in a session).
  Deliberately not in CLAUDE.md/AGENTS.md — those cost agent context every
  session, and this guidance is for the human. Written only on the coding-agent
  path: it's onboarding for commissioning a build, so it doesn't fit a project
  that's already been scaffolded (where the README is the start-here).

After writing AGENTS.md + CLAUDE.md, interactive ``init`` asks how you want to build:
hand off to a coding agent (which later scaffolds with ``pipecat create``), or scaffold
a runnable bot right now (it runs the ``pipecat create`` wizard in-place in the same
directory). ``pipecat init quickstart`` skips the question and scaffolds the canned
quickstart bot in-place — the coding-agent guide *and* a runnable bot in one step.

``pipecat create`` remains the scaffolder itself: coding agents and automation call
it directly (non-interactively); ``init`` is the human entry point that wraps it.

Editing policy for the bundled guide: keep API specifics (signatures, imports,
parameter names) out of AGENTS.md — it is a static snapshot, so anything that
churns belongs in the live sources the guide's §3 points agents at.
"""

import sys
from pathlib import Path

import typer
from rich.console import Console

import pipecat.cli

console = Console()


# Directory holding the bundled AGENTS.md / CLAUDE.md (shipped as package data; see
# pyproject [tool.setuptools.package-data] "pipecat.cli" and MANIFEST.in).
_AGENT_TEMPLATES = Path(pipecat.cli.__file__).parent / "agent_templates"

_AGENTS_FILE = "AGENTS.md"
_CLAUDE_FILE = "CLAUDE.md"
_GETTING_STARTED_FILE = "GETTING_STARTED.md"

# Fixed destination for `pipecat init quickstart`, matching `pipecat create quickstart`.
_QUICKSTART_DIR = "pipecat-quickstart"


def _guide_footer() -> str:
    """Provenance stamp appended to pipecat-owned guide files.

    The written guide is a static snapshot that otherwise looks like hand-written project
    docs. The footer tells a later reader (human or agent) that it is generated and
    refreshable, and which pipecat-ai wrote it — so a project whose pinned version has
    moved on can spot a stale guide.
    """
    return (
        f"\n<!-- Generated by `pipecat init` (pipecat-ai {pipecat.__version__}). "
        "Re-run `pipecat init` to refresh. -->\n"
    )


def _write_agent_guide(target_dir: Path, force: bool) -> None:
    """Write the core agent guide — AGENTS.md and CLAUDE.md — into a directory.

    These set up the project for coding agents and are wanted on *every* path (coding agent,
    scaffold-now, quickstart), so they're written upfront. ``AGENTS.md`` is pipecat-owned
    and always (re)written, so re-running refreshes it after a Pipecat upgrade; ``CLAUDE.md``
    is the developer's own entry point and is only overwritten with ``force``.

    The developer guide (``GETTING_STARTED.md``) is written separately, by
    :func:`_write_developer_guide`, only on the coding-agent path — see
    :func:`_route_build_method`. Exits non-zero on a read/write error.
    """
    try:
        agents_src = (_AGENT_TEMPLATES / _AGENTS_FILE).read_text(encoding="utf-8")
        claude_src = (_AGENT_TEMPLATES / _CLAUDE_FILE).read_text(encoding="utf-8")
    except OSError as e:  # bundled data missing — a packaging regression
        console.print(f"[red]Error: bundled agent guide not found:[/red] {e}")
        raise typer.Exit(1)

    try:
        target_dir.mkdir(parents=True, exist_ok=True)

        agents_path = target_dir / _AGENTS_FILE
        # AGENTS.md is pipecat-owned: always (re)write it so re-running refreshes the guide.
        refreshed = agents_path.exists()
        agents_path.write_text(agents_src + _guide_footer(), encoding="utf-8")
        console.print(f"[green]✔[/green] {'Refreshed' if refreshed else 'Wrote'} {agents_path}")

        claude_path = target_dir / _CLAUDE_FILE
        # CLAUDE.md is the developer's entry point: never clobber an existing one without --force.
        if claude_path.exists() and not force:
            console.print(
                f"[yellow]•[/yellow] Kept existing {claude_path} (use --force to overwrite)."
            )
        else:
            claude_path.write_text(claude_src, encoding="utf-8")
            console.print(f"[green]✔[/green] Wrote {claude_path}")
    except OSError as e:
        console.print(f"[red]Error writing files:[/red] {e}")
        raise typer.Exit(1)


def _write_developer_guide(target_dir: Path) -> None:
    """Write GETTING_STARTED.md — from-scratch developer onboarding — into a directory.

    Written only on the coding-agent path, where the developer is about to commission a
    build. It does *not* fit a project that's just been scaffolded (``Scaffold a runnable
    bot now`` or ``pipecat init quickstart``): there the bot already exists and the
    scaffold's README is the start-here (it carries the Context Hub setup, the one piece a
    just-scaffolded user still needs). Always (re)written, like AGENTS.md; exits non-zero
    on a read/write error.
    """
    try:
        src = (_AGENT_TEMPLATES / _GETTING_STARTED_FILE).read_text(encoding="utf-8")
    except OSError as e:  # bundled data missing — a packaging regression
        console.print(f"[red]Error: bundled agent guide not found:[/red] {e}")
        raise typer.Exit(1)

    try:
        target_dir.mkdir(parents=True, exist_ok=True)
        path = target_dir / _GETTING_STARTED_FILE
        refreshed = path.exists()
        path.write_text(src + _guide_footer(), encoding="utf-8")
        console.print(f"[green]✔[/green] {'Refreshed' if refreshed else 'Wrote'} {path}")
    except OSError as e:
        console.print(f"[red]Error writing files:[/red] {e}")
        raise typer.Exit(1)


def _is_interactive() -> bool:
    """Whether we can show an interactive prompt (a real terminal on both ends)."""
    return sys.stdin.isatty() and sys.stdout.isatty()


def _print_ready(target_dir: Path) -> None:
    """Print the guidance shown when the developer keeps the coding-agent path.

    Names the project directory so the developer knows where to open their session,
    except when init targeted the current directory (``pipecat init .``), where "here"
    reads better than "in .". The agent runs ``pipecat create`` itself (per AGENTS.md),
    so it's left out of this human-facing message.
    """
    where = "here" if target_dir.resolve() == Path.cwd() else f"in [bold]{target_dir}[/bold]"
    console.print(
        f"\n[bold]Your project is ready.[/bold]\n\n"
        f"Read [bold]{_GETTING_STARTED_FILE}[/bold] for how to prompt your agent, then open a "
        f"coding session {where} to start building."
    )


def _route_build_method(target_dir: Path) -> None:
    """Ask whether to build with a coding agent or scaffold a runnable bot now.

    The coding-agent path adds the developer guide (GETTING_STARTED.md) and points the
    developer at their coding session. It's also the default when there's no interactive
    terminal (automation, tests, piped input) or when re-running in an already-scaffolded
    project to refresh the guide. The scaffold path runs the `create` wizard in-place and
    skips the developer guide — the scaffold's README is the start-here for a built bot.
    """
    already_scaffolded = (target_dir / "server").exists()
    if already_scaffolded or not _is_interactive():
        _write_developer_guide(target_dir)
        _print_ready(target_dir)
        return

    import questionary

    from pipecat.cli.prompts.questions import custom_style

    choice = questionary.select(
        "How do you want to build?",
        choices=[
            questionary.Choice("Build with a coding agent (recommended)", value="agent"),
            questionary.Choice("Scaffold a runnable bot now", value="scaffold"),
        ],
        style=custom_style,
    ).ask()

    # `ask()` returns None on Ctrl-C / EOF — fall through to the safe agent path.
    if choice != "scaffold":
        _write_developer_guide(target_dir)
        _print_ready(target_dir)
        return

    # Scaffold now: run the `create` wizard in-place. The scaffold lands in the same
    # directory that already holds AGENTS.md/CLAUDE.md (in-place mode preserves CLAUDE.md),
    # and its README carries the start-here guidance — so no GETTING_STARTED.md here.
    from pipecat.cli.commands.create import scaffold_interactive

    try:
        scaffold_interactive(target_dir, target_dir.name, in_place=True)
    except KeyboardInterrupt:
        console.print("\n[yellow]Project creation cancelled.[/yellow]")
        raise typer.Exit(1)
    except typer.Exit:
        raise
    except FileExistsError as e:
        console.print(f"\n[red]Error: {e}[/red]")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"\n[red]Error creating project: {e}[/red]")
        raise typer.Exit(1)


def _init_quickstart(force: bool) -> None:
    """``pipecat init quickstart``: the canned quickstart, with the coding-agent guide.

    Writes the agent guide into ``pipecat-quickstart/`` and scaffolds the quickstart
    bot in-place there, so the learner's first project is both runnable and set up for
    coding agents. The human counterpart to ``pipecat create quickstart`` (which omits
    the guide). Non-interactive — it's a fixed preset, so there's no build-method
    question.

    Skips ``GETTING_STARTED.md`` (the from-scratch developer onboarding): the bot
    already exists, so the scaffold's README is the start-here.
    """
    from pipecat.cli.commands.create import scaffold_quickstart

    target_dir = Path(_QUICKSTART_DIR)
    # AGENTS.md + CLAUDE.md only — _write_agent_guide never writes GETTING_STARTED.md.
    _write_agent_guide(target_dir, force)
    try:
        scaffold_quickstart(dest=target_dir, in_place=True)
    except typer.Exit:
        raise
    except FileExistsError as e:
        console.print(f"\n[red]Error: {e}[/red]")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"\n[red]Error creating project: {e}[/red]")
        raise typer.Exit(1)


def init_command(
    ctx: typer.Context,
    target: str | None = typer.Argument(
        None,
        help="Directory to initialize (or 'quickstart' for the canned bot). Created if missing.",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        help=f"Also overwrite an existing {_CLAUDE_FILE} ({_AGENTS_FILE} is always refreshed).",
    ),
):
    """Initialize a new Pipecat project, then choose how to build.

    Writes AGENTS.md + CLAUDE.md + GETTING_STARTED.md, then (interactively) hands you
    off to a coding agent or scaffolds a runnable bot in-place with ``pipecat create``.

    Examples::

        pipecat init                 # prompt for a directory, then choose how to build
        pipecat init my-bot          # set up ./my-bot
        pipecat init quickstart      # canned quickstart bot in ./pipecat-quickstart
        pipecat init my-bot --force  # overwrite existing files in ./my-bot
        pipecat init .               # set up the current directory
    """
    # `pipecat init quickstart`: scaffold the canned bot in-place, with the coding-agent guide.
    if target == "quickstart":
        return _init_quickstart(force)

    # The old scaffolder flags (`--name`, `--bot-type`, `--stt`, `-o`, …) belong to
    # `pipecat create`. `ignore_unknown_options` (set at registration) drops them into
    # ctx.args; redirect with a clear message instead of erroring opaquely.
    if ctx.args:
        unexpected = " ".join(ctx.args)
        console.print(
            f"[red]Unexpected arguments:[/red] {unexpected}\n\n"
            "`pipecat init` initializes a new Pipecat project (writes AGENTS.md, CLAUDE.md, "
            "and GETTING_STARTED.md); it takes only an optional target directory and `--force`.\n"
            "To scaffold non-interactively, use [bold]`pipecat create`[/bold] — run "
            "`pipecat create --help`."
        )
        raise typer.Exit(1)

    # No argument: prompt for the directory. `target` is just a path — `.` sets up the
    # current directory, any other value names a folder (created below if it doesn't exist).
    if target is None:
        target = typer.prompt("Project directory", default="pipecat-bot").strip()

    # Validate before any write so a failure never leaves a half-initialized directory.
    target_dir = Path(target or ".")
    if target_dir.exists() and not target_dir.is_dir():
        console.print(f"[red]Error:[/red] {target_dir} exists and is not a directory.")
        raise typer.Exit(1)

    _write_agent_guide(target_dir, force)
    _route_build_method(target_dir)
