version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
  apt_packages:
    - portaudio19-dev
    - python3-dev
    - libasound2-dev
  jobs:
    post_install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs --all-extras --no-extra krisp --no-extra gstreamer --no-extra ultravox --no-extra local_smart_turn --no-extra moondream --no-extra riva --no-extra mlx-whisper

sphinx:
  configuration: docs/api/conf.py
  fail_on_warning: false

search:
  ranking:
    api/*: 5
    getting-started/*: 4
    guides/*: 3

submodules:
  include: all
  recursive: true
