version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
  apt_packages:
    - portaudio19-dev
    - python3-dev
    - libasound2-dev
  jobs:
    pre_build:
      - python -m pip install --upgrade pip
      - pip install wheel setuptools
    post_build:
      - echo "Build completed"

sphinx:
  configuration: docs/api/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/api/requirements.txt
    - method: pip
      path: .

search:
  ranking:
    api/*: 5
    getting-started/*: 4
    guides/*: 3

submodules:
  include: all
  recursive: true
