#
# Copyright (c) 2024-2026, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""Simple text aggregator for basic sentence-boundary text processing.

This module provides a straightforward text aggregator that accumulates text
until it finds an end-of-sentence marker, making it suitable for basic TTS
text processing scenarios.
"""

import re
from collections.abc import AsyncIterator

from loguru import logger

from pipecat.utils.string import SENTENCE_ENDING_PUNCTUATION, match_endofsentence
from pipecat.utils.text.base_text_aggregator import Aggregation, AggregationType, BaseTextAggregator

# Minimum characters before a sentence boundary is allowed to END a chunk.
# Below this we keep accumulating (merging consecutive short sentences) so the TTS
# generates ONE longer, continuously-prosodied utterance instead of many tiny
# clips. Tiny per-sentence clips each generate with a slightly different speaking
# rate/prosody, which is heard as "the voice changing rate" + jumps + ticks at
# every join. We still insert a space after the merged boundary punctuation so the
# TTS pauses naturally at the internal "., ! ?" (no rushed run-on).
_MIN_CHUNK_CHARS: int = 40  # RESTORED from 0. At 0, every sentence boundary fired
# its own tiny TTS clip; on Deepdub (a separate WS synthesis per clip, ~600-900ms
# TTFB each) that was heard as "the voice changing rate" + jumps + cut seams after
# short sentences like "באיזה גודל?" (run 113 — exactly the symptom this comment
# warned about). Merging short sentences up to 40 chars makes the TTS generate ONE
# longer, continuously-prosodied utterance = seamless. Costs a little
# time-to-first-audio on multi-short-sentence replies; worth it (esp. Deepdub).
# Lower toward ~20 only if first-audio latency becomes a problem.

# Mid-sentence splitting is DISABLED for fluency. The user wants joins to happen
# ONLY at real sentence boundaries (". ! ?") so the voice never appears to cut in
# the middle of a sentence — each emitted chunk is a complete sentence (or a few
# merged short ones), generated by the TTS with continuous, natural prosody. We
# keep this equal to the hard safety cap so a comma-split only ever happens to
# rescue a runaway sentence with no end punctuation at all (very rare).
_MAX_PHRASE_CHARS: int = 280

# Absolute safety cap: only if the buffer is enormous AND has no comma do we fall
# back to splitting at a space, to avoid an unbounded utterance. Rare.
_HARD_MAX_CHARS: int = 280

# All single characters (and digraphs) that reliably end a sentence.
# Used both for lookahead triggering and for space-normalization.
_ALL_ENDERS = (
    ".", "!", "?", ";", "…",          # Latin
    "。", "？", "！", "；", "．", "｡",  # East-Asian full-width
    "।", "॥",                          # Devanagari
    "؟", "؛", "۔",                     # Arabic / Urdu
    "།", "།", "።", "፧",              # Tibetan, Ethiopic
    "։", "՜", "՞",                     # Armenian
)
_ALL_ENDERS_SET: frozenset[str] = frozenset(_ALL_ENDERS)

# Strong, UNAMBIGUOUS sentence enders ("!" / "?" and their non-Latin forms): a
# sentence always ends here — unlike "." (decimals, abbreviations) which needs
# lookahead disambiguation. Used by the fast-opener path to emit the FIRST chunk of
# a turn immediately, without waiting for the next token to confirm the boundary.
_STRONG_ENDERS: frozenset[str] = frozenset(("!", "?", "！", "？", "؟", "՜", "՞"))

# Regex: insert a space after a sentence-ending character that is immediately
# followed by a regular (letter) character, e.g. Hebrew "!מ" → "! מ", ".ל" → ". ל".
# The second group EXCLUDES other enders so we never split runs of punctuation
# like "..." or ".." into ". . ." (which produced spurious pauses/fragments).
_ENDERS_ESC = re.escape("".join(_ALL_ENDERS))
_MISSING_SPACE_RE = re.compile(
    r"([" + _ENDERS_ESC + r"])([^\s\d'\"()\[\]" + _ENDERS_ESC + r"])"
)

# Collapse a run of periods possibly separated by spaces ("..", "...", ".. .")
# into a single period. The LLM streams dots as separate tokens, so this must run
# on the assembled sentence (not per-token) to catch them.
_DOT_RUN_RE = re.compile(r"\.(\s*\.)+")
# Collapse a sentence-ender followed by spaces and a stray period into just the
# ender (e.g. "תודה! ." -> "תודה!"), which a newline-after-"!" can produce.
_PUNCT_THEN_DOT_RE = re.compile(r"([!?.;…])\s*\.")


def _clean_sentence(text: str) -> str:
    """Final tidy-up of an assembled chunk before it goes to the TTS."""
    text = _DOT_RUN_RE.sub(".", text)
    text = _PUNCT_THEN_DOT_RE.sub(r"\1", text)
    # Strip stray leading punctuation/space (e.g. a chunk that begins ". תגיד").
    text = text.lstrip(" \t.,;:!?-–—")
    return text.strip()


class SimpleTextAggregator(BaseTextAggregator):
    """Simple text aggregator that accumulates text until sentence boundaries.

    This aggregator provides basic functionality for accumulating text tokens
    and releasing them when an end-of-sentence marker is detected. It's the
    most straightforward implementation of text aggregation for TTS processing.
    """

    def __init__(
        self,
        *,
        min_chunk_chars: int = _MIN_CHUNK_CHARS,
        first_chunk_immediate: bool = True,
        **kwargs,
    ):
        """Initialize the simple text aggregator.

        Creates an empty text buffer ready to begin accumulating text tokens.

        Args:
            min_chunk_chars: Merge sentences until a chunk reaches this many chars.
                A high value (e.g. on Deepdub, which re-synthesizes — with its own
                prosody — every chunk on a fresh connection) makes a whole turn ONE
                continuous synthesis (smooth, consistent voice) at the cost of
                time-to-first-audio. Default keeps the low-latency module value.
            first_chunk_immediate: When True, the FIRST chunk of a turn fires on its
                first sentence boundary for low latency (subsequent sentences still
                merge). Set False to merge the first chunk too (one synthesis/turn).
            **kwargs: Additional arguments passed to BaseTextAggregator (e.g. aggregation_type).
        """
        super().__init__(**kwargs)
        self._text = ""
        self._needs_lookahead: bool = False
        self._emitted_since_reset: bool = False
        self._min_chunk_chars: int = max(0, int(min_chunk_chars))
        self._first_chunk_immediate: bool = first_chunk_immediate

    @property
    def text(self) -> Aggregation:
        """Get the currently aggregated text.

        Returns:
            The text that has been accumulated in the buffer.
        """
        return Aggregation(text=self._text.strip(" "), type=AggregationType.SENTENCE)

    async def aggregate(self, text: str) -> AsyncIterator[Aggregation]:
        """Aggregate text and yield completed aggregations.

        In SENTENCE mode, processes the input text character-by-character. When
        sentence-ending punctuation is detected, it waits for non-whitespace
        lookahead before calling NLTK.

        In TOKEN mode, yields the text immediately without buffering.

        Args:
            text: Text to aggregate.

        Yields:
            Aggregation objects (sentences in SENTENCE mode, tokens in TOKEN mode).
        """
        if self._aggregation_type == AggregationType.TOKEN:
            if text:
                yield Aggregation(text=text, type=AggregationType.TOKEN)
            return

        logger.debug(f"aggregator: received token {text!r} (buffer={len(self._text)} chars)")

        # 1a. Collapse runs of dots (".." / "..." ellipsis) to a single period so
        #     the TTS gets a clean sentence end instead of an odd trailing-off pause.
        text = re.sub(r"\.{2,}", ".", text)

        # 1b. Normalise missing spaces after sentence-ending punctuation so NLTK
        #     can detect boundaries in Hebrew and other scripts that omit spaces.
        text = _MISSING_SPACE_RE.sub(r"\1 \2", text)

        # 2. Treat newlines as hard sentence separators (LLMs frequently emit
        #    "\n" between sentences with no punctuation).
        text = text.replace("\n", ". ")

        # Process text character by character
        for char in text:
            # Sentence-ending punctuation followed immediately by its own kind
            # (e.g. "?!" or "..") should still trigger, but we only add once.
            if char == " " and self._text and self._text[-1] == " ":
                continue  # collapse multiple spaces

            self._text += char

            # Check for sentence with lookahead
            result = await self._check_sentence_with_lookahead(char)
            if result:
                self._emitted_since_reset = True
                yield result
                continue

            # First-clause fast start: emit the OPENING clause at the first
            # comma/clause break (once we have a little text), so TTS starts
            # speaking ~one clause sooner. Gated to the FIRST emission of a turn
            # (_emitted_since_reset) so ONLY the opener is comma-split — the rest of
            # the reply still aggregates at full sentence boundaries (avoids choppy
            # comma-splitting through the whole answer).
            if (
                not self._emitted_since_reset
                and not self._needs_lookahead
                and char in (",", "،", "؛", ";", "—", "–")
                and len(self._text) >= 12
            ):
                phrase = _clean_sentence(self._text)
                if phrase and any(c.isalpha() or c.isdigit() for c in phrase):
                    self._text = ""
                    self._emitted_since_reset = True
                    yield Aggregation(text=phrase, type=AggregationType.SENTENCE)
                    continue

            # Long sentence handling: past _MAX_PHRASE_CHARS with no sentence
            # boundary, split at a COMMA so the long sentence becomes natural
            # breath groups. If there's no comma we keep accumulating (a clean
            # long sentence beats a mid-word cut) until the absolute safety cap.
            if len(self._text) >= _MAX_PHRASE_CHARS and not self._needs_lookahead:
                split_pos = self._find_phrase_split(
                    allow_space=len(self._text) >= _HARD_MAX_CHARS
                )
                if split_pos > 0:
                    phrase = _clean_sentence(self._text[:split_pos])
                    self._text = self._text[split_pos:].lstrip()
                    if phrase:
                        self._emitted_since_reset = True
                        logger.info(
                            f"aggregator: long-sentence split at pos={split_pos} "
                            f"(buffer was {len(phrase) + len(self._text)} chars): {phrase!r}"
                        )
                        yield Aggregation(text=phrase, type=AggregationType.SENTENCE)

    def _find_phrase_split(self, allow_space: bool = False) -> int:
        """Find a position to split a long buffer at a natural pause.

        Prefers the latest comma/semicolon. Only falls back to the last space
        when ``allow_space`` is set (the absolute safety cap) — splitting at an
        arbitrary space mid-sentence sounds like a cut, so we avoid it normally.
        Returns 0 if no acceptable split point is found.
        """
        # Prefer a comma or semicolon in the back half of the buffer.
        search_from = len(self._text) // 3
        for i in range(len(self._text) - 1, search_from, -1):
            if self._text[i] in (",", "،", "؛", ";", "-", "–", "—"):
                return i + 1  # include the comma
        if allow_space:
            last_space = self._text.rfind(" ", search_from)
            if last_space > 0:
                return last_space + 1
        return 0

    async def _check_sentence_with_lookahead(self, char: str) -> Aggregation | None:
        """Check for sentence boundaries using lookahead logic.

        When sentence-ending punctuation is detected we wait for the first
        non-whitespace lookahead character before deciding.  Two cases:

        1. **No gap** (punct immediately before lookahead, e.g. ``"מצוין.ת"``):
           Always a sentence boundary — common in Hebrew/Arabic/CJK where LLMs
           omit the trailing space.

        2. **Space gap** (punct then spaces then lookahead, e.g. ``"End. Next"``):
           Ask NLTK to disambiguate (handles ``"Mr. Smith"`` → not a boundary).
           If NLTK is unsure but the lookahead char is non-ASCII (non-Latin),
           treat it as a boundary anyway (Latin abbreviations don't apply).

        Args:
            char: The most recently added character (used for lookahead check).

        Returns:
            Aggregation if a sentence boundary is confirmed, else None.
        """
        if self._needs_lookahead:
            if not char.strip():
                return None  # Still whitespace — keep waiting

            self._needs_lookahead = False

            # Find the last sentence-ending punctuation in the buffer (it's the
            # one that originally triggered _needs_lookahead = True).
            last_punct_idx = -1
            for i in range(len(self._text) - 2, -1, -1):
                if self._text[i] in _ALL_ENDERS_SET:
                    last_punct_idx = i
                    break

            if last_punct_idx == -1:
                return None  # No punctuation found (shouldn't happen)

            # Text between the triggering punctuation and the current lookahead
            # char. Because _needs_lookahead fires on the *first* non-space char,
            # this region can only contain whitespace (or be empty).
            between = self._text[last_punct_idx + 1 : len(self._text) - 1]
            has_space_gap = bool(between)  # True when there are spaces in between

            eos_marker = 0
            if not has_space_gap:
                # No space between punct and next char.
                # Guard: digit after punct = decimal number (e.g. "29.5") → no split.
                # Guard: punct after punct = consecutive marks (e.g. "..") → no split here,
                #         the outer punct already set _needs_lookahead for the next char.
                if char.isdigit() or char in _ALL_ENDERS_SET:
                    eos_marker = 0
                else:
                    # Definite sentence boundary (e.g. Hebrew "מצוין.ת", "נתניהו!הוא")
                    eos_marker = last_punct_idx + 1
            else:
                # Space(s) between punct and next char: let NLTK disambiguate.
                eos_marker = match_endofsentence(self._text)

                if eos_marker == 0 and not char.isascii():
                    # NLTK couldn't confirm, but the next char is non-Latin
                    # (Hebrew, Arabic, etc.) — definitely a new sentence because
                    # those scripts don't use Latin-style abbreviations with ".".
                    eos_marker = last_punct_idx + 1

            if eos_marker:
                candidate = self._text[:eos_marker].strip()

                # Merge short chunks: if the accumulated text is still shorter than
                # _MIN_CHUNK_CHARS, do NOT split here. Keep accumulating so the TTS
                # gets a longer, continuously-generated utterance. Crucially, when
                # the boundary had no trailing space (Hebrew "מצוין.מה", common when
                # the LLM streams "." and the next word as separate tokens), insert a
                # space after the punctuation on the BUFFER so the merged text reads
                # "מצוין. מה" — the TTS then pauses naturally at the internal period
                # instead of rushing through a run-on.
                # Merge short sentences ONLY after the first chunk. The first chunk
                # must fire on its first sentence boundary for low time-to-first-audio
                # — merging it made a short opener wait to accumulate 40 chars (often
                # the whole reply), which is the latency regression in run 124.
                # Subsequent short sentences still merge (seamless tail); their latency
                # hides behind the first chunk's playback.
                if len(candidate) < self._min_chunk_chars and (
                    self._emitted_since_reset or not self._first_chunk_immediate
                ):
                    if not has_space_gap:
                        self._text = (
                            self._text[: last_punct_idx + 1]
                            + " "
                            + self._text[last_punct_idx + 1 :]
                        )
                    return None

                result = _clean_sentence(candidate)
                self._text = self._text[eos_marker:].lstrip(" ")
                # Skip fragments that are only punctuation marks (e.g. lone ".")
                if result and any(c.isalpha() or c.isdigit() for c in result):
                    logger.debug(
                        f"aggregator: yielding chunk ({len(result)} chars, "
                        f"has_space_gap={has_space_gap}): {result!r}"
                    )
                    return Aggregation(text=result, type=AggregationType.SENTENCE)
                else:
                    logger.debug(f"aggregator: skipped punct-only fragment: {result!r}")

            return None

        # Fast opener: "!" and "?" are UNAMBIGUOUS sentence ends (never decimals or
        # abbreviations), so for the FIRST chunk of a turn emit IMMEDIATELY without
        # waiting for the lookahead char. That lookahead otherwise stalls the opening
        # clause until the NEXT token streams in — pure time-to-first-audio cost.
        # Subsequent sentences keep the careful lookahead path (handles "?!" and
        # run-on punctuation); their latency hides behind the prior chunk's synthesis.
        if (
            self._first_chunk_immediate
            and not self._emitted_since_reset
            and not self._needs_lookahead
            and self._text
            and self._text[-1] in _STRONG_ENDERS
        ):
            candidate = self._text.strip()
            # Fire the first chunk immediately on a strong ender — NO _MIN_CHUNK_CHARS
            # gate here. That gate blocked the opener for a short first sentence
            # ("מצוין, תודה ששאלתם!" = 19 chars < 40), forcing it to wait for the
            # whole reply = the latency regression (run 124).
            if any(c.isalpha() or c.isdigit() for c in candidate):
                result = _clean_sentence(candidate)
                if result and any(c.isalpha() or c.isdigit() for c in result):
                    self._text = ""
                    return Aggregation(text=result, type=AggregationType.SENTENCE)

        # Check if we just added sentence-ending punctuation
        if self._text and self._text[-1] in _ALL_ENDERS_SET:
            self._needs_lookahead = True

        return None

    async def flush(self) -> Aggregation | None:
        """Flush any remaining text in the buffer.

        Returns any text remaining in the buffer. This is called at the end
        of a stream to ensure all text is processed. In TOKEN mode, returns
        None since tokens are yielded immediately.

        Returns:
            Any remaining text as a sentence, or None if buffer is empty or in TOKEN mode.
        """
        if self._aggregation_type == AggregationType.TOKEN:
            return None

        if self._text:
            result = _clean_sentence(self._text)
            await self.reset()
            logger.debug(f"aggregator: flush remaining ({len(result)} chars): {result!r}")
            return Aggregation(text=result, type=AggregationType.SENTENCE)
        return None

    async def handle_interruption(self):
        """Handle interruptions by clearing the text buffer.

        Called when an interruption occurs in the processing pipeline,
        discarding any partially accumulated text.
        """
        self._text = ""
        self._needs_lookahead = False
        self._emitted_since_reset = False

    async def reset(self):
        """Clear the internally aggregated text.

        Resets the aggregator to its initial empty state, discarding
        any accumulated text content.
        """
        self._text = ""
        self._needs_lookahead = False
        self._emitted_since_reset = False
