import argparse
import asyncio
import requests

from dailyai.services.daily_transport_service import DailyTransportService
from dailyai.services.azure_ai_services import AzureLLMService, AzureTTSService
from dailyai.output_queue import OutputQueueFrame, FrameType

async def main(room_url:str, token):
    global transport
    global llm
    global tts

    transport = DailyTransportService(
        room_url,
        token,
        "Say Two Things Bot",
        1,
    )
    transport.mic_enabled = True
    transport.mic_sample_rate = 16000
    transport.camera_enabled = False

    llm = AzureLLMService()
    tts = AzureTTSService()

    @transport.event_handler("on_participant_joined")
    async def on_joined(transport, participant):
        if participant["id"] == transport.my_participant_id:
            return

        # queue two pieces of speech: one specified as a text literal,
        # and one generated by an llm. We'll kick off the llm first, and let
        # it generate a response while we're speaking the literal string.
        llm_response_task = asyncio.create_task(llm.run_llm(
            [{"role": "system", "content": "tell the user a joke about llamas"}]
        ))

        async for audio_chunk in tts.run_tts("My friend the LLM is now going to tell a joke about llamas."):
            transport.output_queue.put(OutputQueueFrame(FrameType.AUDIO_FRAME, audio_chunk))

        llm_response = await llm_response_task
        async for audio_chunk in tts.run_tts(llm_response):
            transport.output_queue.put(OutputQueueFrame(FrameType.AUDIO_FRAME, audio_chunk))

        # wait for the output queue to be empty, then leave the meeting
        transport.output_queue.join()
        transport.stop()

    @transport.event_handler("on_transcription_message")
    async def on_transcription_message(transport, message) -> None:
        print("message received", message)

    await transport.run()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Simple Daily Bot Sample")
    parser.add_argument(
        "-u", "--url", type=str, required=True, help="URL of the Daily room to join"
    )
    parser.add_argument(
        "-k",
        "--apikey",
        type=str,
        required=True,
        help="Daily API Key (needed to create token)",
    )

    args: argparse.Namespace = parser.parse_args()

    # Create a meeting token for the given room with an expiration 1 hour in the future.
    room_name: str = urllib.parse.urlparse(args.url).path[1:]
    expiration: float = time.time() + 60 * 60

    res: requests.Response = requests.post(
        f"https://api.daily.co/v1/meeting-tokens",
        headers={"Authorization": f"Bearer {args.apikey}"},
        json={
            "properties": {"room_name": room_name, "is_owner": True, "exp": expiration}
        },
    )

    if res.status_code != 200:
        raise Exception(f"Failed to create meeting token: {res.status_code} {res.text}")

    token: str = res.json()["token"]

    asyncio.run(main(args.url, token))
