FROM dailyco/pipecat-base:latest

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Uncomment if you wish to print a summary of the features available in the base image
# ENV PCC_LOG_FEATURES_SUMMARY=true

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev

# Copy the application code
{% if 'daily_pstn_dialin' in transports or 'daily_pstn_dialout' in transports or 'twilio_daily_sip_dialin' in transports or 'twilio_daily_sip_dialout' in transports %}
COPY ./server_utils.py server_utils.py
{% endif %}
COPY ./bot.py bot.py
