"""AUTO-GENERATED SERVICE CONFIGURATIONS.

⚠️  DO NOT EDIT THIS FILE DIRECTLY ⚠️

This file is automatically generated from service_metadata.py.
To make changes, edit service_metadata.py and run:
  uv run scripts/cli/update_registry.py

Source: scripts/cli/configs/config_generator.py
"""

SERVICE_CONFIGS = {
    # STT Services
    "assemblyai_stt": 'AssemblyAISTTService(api_key=os.getenv("ASSEMBLYAI_API_KEY"))',
    "aws_transcribe_stt": (
        "AWSTranscribeSTTService(\n"
        '        aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),\n'
        '        aws_session_token=os.getenv("AWS_AWS_SESSION_TOKEN"),\n'
        '        region=os.getenv("AWS_REGION")\n'
        "    )\n"
    ),
    "azure_stt": (
        "AzureSTTService(\n"
        '        api_key=os.getenv("AZURE_SPEECH_API_KEY"),\n'
        '        region=os.getenv("AZURE_SPEECH_REGION")\n'
        "    )\n"
    ),
    "cartesia_stt": 'CartesiaSTTService(api_key=os.getenv("CARTESIA_API_KEY"))',
    "cartesia_turns_stt": 'CartesiaTurnsSTTService(api_key=os.getenv("CARTESIA_API_KEY"))',
    "deepgram_stt": 'DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))',
    "deepgram_flux_stt": 'DeepgramFluxSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))',
    "deepgram_flux_sagemaker_stt": (
        "DeepgramFluxSageMakerSTTService(\n"
        '        endpoint_name=os.getenv("DEEPGRAM_FLUX_SAGEMAKER_STT_ENDPOINT_NAME"),\n'
        '        region=os.getenv("DEEPGRAM_FLUX_SAGEMAKER_STT_REGION")\n'
        "    )\n"
    ),
    "deepgram_sagemaker_stt": (
        "DeepgramSageMakerSTTService(\n"
        '        endpoint_name=os.getenv("DEEPGRAM_SAGEMAKER_STT_ENDPOINT_NAME"),\n'
        '        region=os.getenv("DEEPGRAM_SAGEMAKER_STT_REGION")\n'
        "    )\n"
    ),
    "elevenlabs_stt": (
        "ElevenLabsSTTService(\n"
        '        api_key=os.getenv("ELEVENLABS_API_KEY"),\n'
        "        aiohttp_session=session\n"
        "    )\n"
    ),
    "elevenlabs_realtime_stt": 'ElevenLabsRealtimeSTTService(api_key=os.getenv("ELEVENLABS_API_KEY"))',
    "fal_stt": (
        "FalSTTService(\n"
        '        api_key=os.getenv("FAL_API_KEY"),\n'
        "        aiohttp_session=session\n"
        "    )\n"
    ),
    "gladia_stt": (
        "GladiaSTTService(\n"
        '        api_key=os.getenv("GLADIA_API_KEY"),\n'
        '        region=os.getenv("GLADIA_REGION")\n'
        "    )\n"
    ),
    "google_stt": (
        "GoogleSTTService(\n"
        '        credentials=os.getenv("GOOGLE_APPLICATION_CREDENTIALS"),\n'
        '        location=os.getenv("GOOGLE_LOCATION")\n'
        "    )\n"
    ),
    "gradium_stt": 'GradiumSTTService(api_key=os.getenv("GRADIUM_API_KEY"))',
    "groq_stt": 'GroqSTTService(api_key=os.getenv("GROQ_API_KEY"))',
    "mistral_stt": 'MistralSTTService(api_key=os.getenv("MISTRAL_API_KEY"))',
    "nvidia_stt": 'NvidiaSTTService(api_key=os.getenv("NVIDIA_API_KEY"))',
    "nvidia_sagemaker_stt": (
        "NvidiaSageMakerSTTService(\n"
        '    endpoint_name=os.getenv("NVIDIA_SAGEMAKER_STT_ENDPOINT_NAME"),\n'
        '    region=os.getenv("AWS_REGION")\n'
        ")\n"
    ),
    "openai_stt": 'OpenAISTTService(api_key=os.getenv("OPENAI_API_KEY"))',
    "openai_realtime_stt": 'OpenAIRealtimeSTTService(api_key=os.getenv("OPENAI_API_KEY"))',
    "sarvam_stt": (
        "SarvamSTTService(\n"
        '        api_key=os.getenv("SARVAM_API_KEY"),\n'
        "        settings=SarvamSTTService.Settings(\n"
        '            model=os.getenv("SARVAM_MODEL"),\n'
        "        ),\n"
        "    )\n"
    ),
    "soniox_stt": 'SonioxSTTService(api_key=os.getenv("SONIOX_API_KEY"))',
    "speechmatics_stt": 'SpeechmaticsSTTService(api_key=os.getenv("SPEECHMATICS_API_KEY"))',
    "moonshine_stt": (
        "MoonshineSTTService(\n"
        "        settings=MoonshineSTTService.Settings(\n"
        '            model=os.getenv("MOONSHINE_STT_MODEL"),\n'
        "        ),\n"
        "    )\n"
    ),
    "whisper_stt": (
        "WhisperSTTService(\n"
        "        settings=WhisperSTTService.Settings(\n"
        '            model=os.getenv("OPENAI_MODEL"),\n'
        "        ),\n"
        "    )\n"
    ),
    "xai_stt": 'XAISTTService(api_key=os.getenv("XAI_API_KEY"))',
    # LLM Services
    "anthropic_llm": (
        "AnthropicLLMService(\n"
        '        api_key=os.getenv("ANTHROPIC_API_KEY"),\n'
        "        settings=AnthropicLLMService.Settings(\n"
        '            model=os.getenv("ANTHROPIC_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "aws_bedrock_llm": (
        "AWSBedrockLLMService(\n"
        '    aws_region=os.getenv("AWS_REGION"),\n'
        "    settings=AWSBedrockLLMService.Settings(\n"
        '        model=os.getenv("AWS_BEDROCK_MODEL"),\n'
        '        system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "    ),\n"
        ")\n"
    ),
    "azure_llm": (
        "AzureLLMService(\n"
        '        api_key=os.getenv("AZURE_CHATGPT_API_KEY"),\n'
        '        endpoint=os.getenv("AZURE_CHATGPT_ENDPOINT"),\n'
        "        settings=AzureLLMService.Settings(\n"
        '            model=os.getenv("AZURE_CHATGPT_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "cerebras_llm": (
        "CerebrasLLMService(\n"
        '        api_key=os.getenv("CEREBRAS_API_KEY"),\n'
        "        settings=CerebrasLLMService.Settings(\n"
        '            model=os.getenv("CEREBRAS_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "crusoe_llm": (
        "CrusoeLLMService(\n"
        '        api_key=os.getenv("CRUSOE_API_KEY"),\n'
        "        settings=CrusoeLLMService.Settings(\n"
        '            model=os.getenv("CRUSOE_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "deepseek_llm": (
        "DeepSeekLLMService(\n"
        '        api_key=os.getenv("DEEPSEEK_API_KEY"),\n'
        "        settings=DeepSeekLLMService.Settings(\n"
        '            model=os.getenv("DEEPSEEK_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "fireworks_llm": (
        "FireworksLLMService(\n"
        '        api_key=os.getenv("FIREWORKS_API_KEY"),\n'
        "        settings=FireworksLLMService.Settings(\n"
        '            model=os.getenv("FIREWORKS_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "google_gemini_llm": (
        "GoogleLLMService(\n"
        '        api_key=os.getenv("GOOGLE_API_KEY"),\n'
        "        settings=GoogleLLMService.Settings(\n"
        '            model=os.getenv("GOOGLE_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "google_vertex_llm": (
        "GoogleVertexLLMService(\n"
        '        credentials=os.getenv("GOOGLE_APPLICATION_CREDENTIALS"),\n'
        '        location=os.getenv("GOOGLE_LOCATION"),\n'
        '        project_id=os.getenv("GOOGLE_PROJECT_ID"),\n'
        "        settings=GoogleVertexLLMService.Settings(\n"
        '            model=os.getenv("GOOGLE_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "xai_llm": (
        "GrokLLMService(\n"
        '        api_key=os.getenv("XAI_API_KEY"),\n'
        "        settings=GrokLLMService.Settings(\n"
        '            model=os.getenv("XAI_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "groq_llm": (
        "GroqLLMService(\n"
        '        api_key=os.getenv("GROQ_API_KEY"),\n'
        "        settings=GroqLLMService.Settings(\n"
        '            model=os.getenv("GROQ_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "inception_llm": (
        "InceptionLLMService(\n"
        '        api_key=os.getenv("INCEPTION_API_KEY"),\n'
        "        settings=InceptionLLMService.Settings(\n"
        '            model=os.getenv("INCEPTION_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "mistral_llm": (
        "MistralLLMService(\n"
        '        api_key=os.getenv("MISTRAL_API_KEY"),\n'
        "        settings=MistralLLMService.Settings(\n"
        '            model=os.getenv("MISTRAL_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "novita_llm": (
        "NovitaLLMService(\n"
        '        api_key=os.getenv("NOVITA_API_KEY"),\n'
        "        settings=NovitaLLMService.Settings(\n"
        '            model=os.getenv("NOVITA_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "nvidia_llm": (
        "NvidiaLLMService(\n"
        '        api_key=os.getenv("NVIDIA_API_KEY"),\n'
        "        settings=NvidiaLLMService.Settings(\n"
        '            model=os.getenv("NVIDIA_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "ollama_llm": (
        "OLLamaLLMService(\n"
        "        settings=OLLamaLLMService.Settings(\n"
        '            model=os.getenv("OLLAMA_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "openai_llm": (
        "OpenAILLMService(\n"
        '        api_key=os.getenv("OPENAI_API_KEY"),\n'
        "        settings=OpenAILLMService.Settings(\n"
        '            model=os.getenv("OPENAI_MODEL", "gpt-4.1"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "openai_responses_llm": (
        "OpenAIResponsesLLMService(\n"
        '        api_key=os.getenv("OPENAI_API_KEY"),\n'
        "        settings=OpenAIResponsesLLMService.Settings(\n"
        '            model=os.getenv("OPENAI_MODEL", "gpt-4.1"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "openrouter_llm": (
        "OpenRouterLLMService(\n"
        '        api_key=os.getenv("OPENROUTER_API_KEY"),\n'
        "        settings=OpenRouterLLMService.Settings(\n"
        '            model=os.getenv("OPENROUTER_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "perplexity_llm": (
        "PerplexityLLMService(\n"
        '        api_key=os.getenv("PERPLEXITY_API_KEY"),\n'
        "        settings=PerplexityLLMService.Settings(\n"
        '            model=os.getenv("PERPLEXITY_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "qwen_llm": (
        "QwenLLMService(\n"
        '        api_key=os.getenv("QWEN_API_KEY"),\n'
        "        settings=QwenLLMService.Settings(\n"
        '            model=os.getenv("QWEN_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "sambanova_llm": (
        "SambaNovaLLMService(\n"
        '        api_key=os.getenv("SAMBANOVA_API_KEY"),\n'
        "        settings=SambaNovaLLMService.Settings(\n"
        '            model=os.getenv("SAMBANOVA_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "sarvam_llm": (
        "SarvamLLMService(\n"
        '        api_key=os.getenv("SARVAM_API_KEY"),\n'
        "        settings=SarvamLLMService.Settings(\n"
        '            model=os.getenv("SARVAM_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    "together_llm": (
        "TogetherLLMService(\n"
        '        api_key=os.getenv("TOGETHER_API_KEY"),\n'
        "        settings=TogetherLLMService.Settings(\n"
        '            model=os.getenv("TOGETHER_MODEL"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    )\n"
    ),
    # TTS Services
    "asyncai_tts": (
        "AsyncAITTSService(\n"
        '        api_key=os.getenv("ASYNCAI_API_KEY"),\n'
        "        settings=AsyncAITTSService.Settings(\n"
        '            voice=os.getenv("ASYNCAI_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "aws_polly_tts": (
        "AWSPollyTTSService(\n"
        '        region=os.getenv("AWS_REGION"),\n'
        "        settings=AWSPollyTTSService.Settings(\n"
        '            voice=os.getenv("AWS_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "azure_tts": (
        "AzureTTSService(\n"
        '        api_key=os.getenv("AZURE_SPEECH_API_KEY"),\n'
        '        region=os.getenv("AZURE_SPEECH_REGION"),\n'
        "        settings=AzureTTSService.Settings(\n"
        '            voice=os.getenv("AZURE_SPEECH_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "camb_tts": (
        "CambTTSService(\n"
        '        api_key=os.getenv("CAMB_API_KEY"),\n'
        "        settings=CambTTSService.Settings(\n"
        '            voice=os.getenv("CAMB_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "cartesia_tts": (
        "CartesiaTTSService(\n"
        '        api_key=os.getenv("CARTESIA_API_KEY"),\n'
        "        settings=CartesiaTTSService.Settings(\n"
        '            voice=os.getenv("CARTESIA_VOICE_ID", "71a7ad14-091c-4e8e-a314-022ece01c121"),\n'
        "        ),\n"
        "    )\n"
    ),
    "deepgram_tts": (
        "DeepgramTTSService(\n"
        '        api_key=os.getenv("DEEPGRAM_API_KEY"),\n'
        "        settings=DeepgramTTSService.Settings(\n"
        '            voice=os.getenv("DEEPGRAM_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "deepgram_sagemaker_tts": (
        "DeepgramSageMakerTTSService(\n"
        '        endpoint_name=os.getenv("DEEPGRAM_SAGEMAKER_TTS_ENDPOINT_NAME"),\n'
        '        region=os.getenv("DEEPGRAM_SAGEMAKER_TTS_REGION"),\n'
        "        settings=DeepgramSageMakerTTSService.Settings(\n"
        '            voice=os.getenv("DEEPGRAM_SAGEMAKER_TTS_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "elevenlabs_tts": (
        "ElevenLabsTTSService(\n"
        '        api_key=os.getenv("ELEVENLABS_API_KEY"),\n'
        "        settings=ElevenLabsTTSService.Settings(\n"
        '            voice=os.getenv("ELEVENLABS_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "fish_tts": (
        "FishAudioTTSService(\n"
        '        api_key=os.getenv("FISH_API_KEY"),\n'
        "        settings=FishAudioTTSService.Settings(\n"
        '            voice=os.getenv("FISH_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "gemini_tts": (
        "GeminiTTSService(\n"
        '        credentials=os.getenv("GOOGLE_APPLICATION_CREDENTIALS"),\n'
        "        settings=GeminiTTSService.Settings(\n"
        '            voice=os.getenv("GOOGLE_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "google_tts": (
        "GoogleTTSService(\n"
        '        credentials=os.getenv("GOOGLE_APPLICATION_CREDENTIALS"),\n'
        "        settings=GoogleTTSService.Settings(\n"
        '            voice=os.getenv("GOOGLE_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "gradium_tts": (
        "GradiumTTSService(\n"
        '        api_key=os.getenv("GRADIUM_API_KEY"),\n'
        "        settings=GradiumTTSService.Settings(\n"
        '            voice=os.getenv("GRADIUM_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "groq_tts": (
        "GroqTTSService(\n"
        '        api_key=os.getenv("GROQ_API_KEY"),\n'
        "        settings=GroqTTSService.Settings(\n"
        '            voice=os.getenv("GROQ_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "hume_tts": (
        "HumeTTSService(\n"
        '        api_key=os.getenv("HUME_API_KEY"),\n'
        "        settings=HumeTTSService.Settings(\n"
        '            voice=os.getenv("HUME_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "inworld_tts": (
        "InworldTTSService(\n"
        '        api_key=os.getenv("INWORLD_API_KEY"),\n'
        "        settings=InworldTTSService.Settings(\n"
        '            voice=os.getenv("INWORLD_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "kokoro_tts": (
        "KokoroTTSService(\n"
        "        settings=KokoroTTSService.Settings(\n"
        '            voice=os.getenv("KOKORO_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "lmnt_tts": (
        "LmntTTSService(\n"
        '        api_key=os.getenv("LMNT_API_KEY"),\n'
        "        settings=LmntTTSService.Settings(\n"
        '            voice=os.getenv("LMNT_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "minimax_tts": (
        "MiniMaxHttpTTSService(\n"
        '        api_key=os.getenv("MINIMAX_API_KEY"),\n'
        '        group_id=os.getenv("MINIMAX_GROUP_ID"),\n'
        "        aiohttp_session=session,\n"
        "        settings=MiniMaxHttpTTSService.Settings(\n"
        '            voice=os.getenv("MINIMAX_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "mistral_tts": (
        "MistralTTSService(\n"
        '        api_key=os.getenv("MISTRAL_API_KEY"),\n'
        "        settings=MistralTTSService.Settings(\n"
        '            voice=os.getenv("MISTRAL_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "neuphonic_tts": (
        "NeuphonicTTSService(\n"
        '        api_key=os.getenv("NEUPHONIC_API_KEY"),\n'
        "        settings=NeuphonicTTSService.Settings(\n"
        '            voice=os.getenv("NEUPHONIC_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "nvidia_tts": (
        "NvidiaTTSService(\n"
        '        api_key=os.getenv("NVIDIA_API_KEY"),\n'
        "        settings=NvidiaTTSService.Settings(\n"
        '            voice=os.getenv("NVIDIA_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "nvidia_sagemaker_tts": (
        "NvidiaSageMakerTTSService(\n"
        '    endpoint_name=os.getenv("NVIDIA_SAGEMAKER_TTS_ENDPOINT_NAME"),\n'
        '    region=os.getenv("AWS_REGION"),\n'
        "    settings=NvidiaSageMakerTTSService.Settings(\n"
        '        voice=os.getenv("NVIDIA_SAGEMAKER_TTS_VOICE_ID"),\n'
        "    ),\n"
        ")\n"
    ),
    "openai_tts": (
        "OpenAITTSService(\n"
        '        api_key=os.getenv("OPENAI_API_KEY"),\n'
        "        settings=OpenAITTSService.Settings(\n"
        '            voice=os.getenv("OPENAI_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "piper_tts": (
        "PiperTTSService(\n"
        "        settings=PiperTTSService.Settings(\n"
        '            voice=os.getenv("PIPER_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "resemble_tts": (
        "ResembleAITTSService(\n"
        '        api_key=os.getenv("RESEMBLE_API_KEY"),\n'
        "        settings=ResembleAITTSService.Settings(\n"
        '            voice=os.getenv("RESEMBLE_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "rime_tts": (
        "RimeTTSService(\n"
        '        api_key=os.getenv("RIME_API_KEY"),\n'
        "        settings=RimeTTSService.Settings(\n"
        '            voice=os.getenv("RIME_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "sarvam_tts": (
        "SarvamTTSService(\n"
        '        api_key=os.getenv("SARVAM_API_KEY"),\n'
        "        settings=SarvamTTSService.Settings(\n"
        '            model=os.getenv("SARVAM_MODEL"),\n'
        '            voice=os.getenv("SARVAM_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "smallest_tts": (
        "SmallestTTSService(\n"
        '        api_key=os.getenv("SMALLEST_API_KEY"),\n'
        "        settings=SmallestTTSService.Settings(\n"
        '            voice=os.getenv("SMALLEST_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "soniox_tts": (
        "SonioxTTSService(\n"
        '        api_key=os.getenv("SONIOX_API_KEY"),\n'
        "        settings=SonioxTTSService.Settings(\n"
        '            voice=os.getenv("SONIOX_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "xai_tts": (
        "XAITTSService(\n"
        '        api_key=os.getenv("XAI_API_KEY"),\n'
        "        settings=XAITTSService.Settings(\n"
        '            voice=os.getenv("XAI_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    "xtts_tts": (
        "XTTSService(\n"
        '        base_url=os.getenv("XTTS_BASE_URL"),\n'
        "        aiohttp_session=session,\n"
        "        settings=XTTSService.Settings(\n"
        '            voice=os.getenv("XTTS_VOICE_ID"),\n'
        "        ),\n"
        "    )\n"
    ),
    # Realtime Services
    "aws_nova_realtime": (
        "llm = AWSNovaSonicLLMService(\n"
        '    secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),\n'
        '    access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),\n'
        '    region=os.getenv("AWS_REGION"),\n'
        '    session_token=os.getenv("AWS_SESSION_TOKEN"),\n'
        "    settings=AWSNovaSonicLLMService.Settings(\n"
        '        voice=os.getenv("AWS_VOICE_ID"),\n'
        '        system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "    ),\n"
        ")\n"
    ),
    "azure_realtime": (
        "session_properties = SessionProperties(\n"
        '    input_audio_transcription=InputAudioTranscription(model="whisper-1"),\n'
        ")\n"
        "llm = AzureRealtimeLLMService(\n"
        '    api_key=os.getenv("AZURE_REALTIME_API_KEY"),\n'
        '    base_url=os.getenv("AZURE_REALTIME_BASE_URL"),\n'
        "    settings=AzureRealtimeLLMService.Settings(\n"
        "        session_properties=session_properties,\n"
        '        system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "    ),\n"
        ")\n"
    ),
    "gemini_live_realtime": (
        "llm = GeminiLiveLLMService(\n"
        '    api_key=os.getenv("GOOGLE_API_KEY"),\n'
        "    settings=GeminiLiveLLMService.Settings(\n"
        '        model=os.getenv("GOOGLE_MODEL"),\n'
        '        voice=os.getenv("GOOGLE_VOICE_ID"),\n'
        '        system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "    ),\n"
        ")\n"
    ),
    "gemini_vertex_live_realtime": (
        "llm = GeminiLiveVertexLLMService(\n"
        '        credentials=os.getenv("GOOGLE_APPLICATION_CREDENTIALS"),\n'
        '        project_id=os.getenv("GOOGLE_PROJECT_ID"),\n'
        '        location=os.getenv("GOOGLE_LOCATION"),\n'
        "        settings=GeminiLiveVertexLLMService.Settings(\n"
        '            model=os.getenv("GOOGLE_MODEL"),\n'
        '            voice=os.getenv("GOOGLE_VOICE_ID"),\n'
        '            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "        ),\n"
        "    ),\n"
        ")\n"
    ),
    "xai_realtime": (
        "session_properties = SessionProperties(\n"
        '    voice=os.getenv("XAI_VOICE_ID"),\n'
        ")\n"
        "llm = GrokRealtimeLLMService(\n"
        '    api_key=os.getenv("XAI_API_KEY"),\n'
        "    settings=GrokRealtimeLLMService.Settings(\n"
        "        session_properties=session_properties,\n"
        '        system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "    ),\n"
        ")\n"
    ),
    "openai_realtime": (
        "session_properties = SessionProperties(\n"
        "    audio=AudioConfiguration(\n"
        "        input=AudioInput(\n"
        "            transcription=InputAudioTranscription(),\n"
        "            turn_detection=SemanticTurnDetection(),\n"
        '            noise_reduction=InputAudioNoiseReduction(type="near_field"),\n'
        "        )\n"
        "    ),\n"
        ")\n"
        "llm = OpenAIRealtimeLLMService(\n"
        '    api_key=os.getenv("OPENAI_API_KEY"),\n'
        "    settings=OpenAIRealtimeLLMService.Settings(\n"
        "        session_properties=session_properties,\n"
        '        system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can\'t be spoken. Respond to what the user said in a creative, helpful, and brief way.",\n'
        "    ),\n"
        ")\n"
    ),
    "ultravox": (
        "llm =UltravoxRealtimeLLMService(\n"
        "    params=OneShotInputParams(\n"
        '        api_key=os.getenv("ULTRAVOX_API_KEY"),\n'
        '        system_prompt=os.getenv("ULTRAVOX_SYSTEM_PROMPT"),\n'
        "        temperature=0.3,\n"
        "        max_duration=datetime.timedelta(minutes=3),\n"
        "    ),\n"
        ")\n"
    ),
    # Video Services
    "heygen_video": (
        "HeyGenVideoService(\n"
        '    api_key=os.getenv("HEYGEN_API_KEY"),\n'
        "    service_type=ServiceType.LIVE_AVATAR,\n"
        "    session=session,\n"
        "    session_request=LiveAvatarNewSessionRequest(\n"
        '        avatar_id="HEYGEN_AVATAR_ID",\n'
        "    ),\n"
        ")\n"
    ),
    "tavus_video": (
        "TavusVideoService(\n"
        '        api_key=os.getenv("TAVUS_API_KEY"),\n'
        '        replica_id=os.getenv("TAVUS_REPLICA_ID"),\n'
        "        session=session\n"
        "    )\n"
    ),
    "simli_video": (
        "SimliVideoService(\n"
        '        api_key=os.getenv("SIMLI_API_KEY"),\n'
        '        face_id=os.getenv("SIMLI_FACE_ID")\n'
        "    )\n"
    ),
}
