"""AUTO-GENERATED SERVICE IMPORTS.

⚠️  DO NOT EDIT THIS FILE DIRECTLY ⚠️

This file is automatically generated from service_metadata.py.
To make changes, edit service_metadata.py and run:
  uv run scripts/cli/update_registry.py

Source: scripts/cli/imports/import_generator.py
"""

# Import statements mapping for services and transports
IMPORTS = {
    # Transports - WebRTC
    "daily": ["from pipecat.transports.daily.transport import DailyParams"],
    "smallwebrtc": ["from pipecat.transports.base_transport import TransportParams"],
    "websocket": [
        "from pipecat.serializers.protobuf import ProtobufFrameSerializer",
        "from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams",
    ],
    # Transports - Telephony
    "twilio": [
        "from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams",
        "import aiohttp",
        "from pydantic import BaseModel",
    ],
    "twilio_daily_sip_dialin": [
        "from pipecat.transports.daily.transport import DailyParams, DailyTransport",
        "from server_utils import AgentRequest",
        "from twilio.rest import Client",
    ],
    "twilio_daily_sip_dialout": [
        "from pipecat.transports.daily.transport import DailyParams, DailyTransport",
        "from server_utils import AgentRequest, DialoutSettings",
        "from typing import Any",
    ],
    "daily_pstn_dialin": [
        "from pipecat.transports.daily.transport import DailyParams",
        "from pipecat.runner.types import DailyDialinRequest",
    ],
    "daily_pstn_dialout": [
        "from pipecat.transports.daily.transport import DailyParams, DailyTransport",
        "from server_utils import AgentRequest, DialoutSettings",
        "from typing import Any",
    ],
    "telnyx": ["from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams"],
    "plivo": ["from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams"],
    "exotel": ["from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams"],
    # STT Services
    "assemblyai_stt": ["from pipecat.services.assemblyai.stt import AssemblyAISTTService"],
    "aws_transcribe_stt": ["from pipecat.services.aws.stt import AWSTranscribeSTTService"],
    "azure_stt": ["from pipecat.services.azure.stt import AzureSTTService"],
    "cartesia_stt": ["from pipecat.services.cartesia.stt import CartesiaSTTService"],
    "cartesia_turns_stt": [
        "from pipecat.services.cartesia.turns.stt import CartesiaTurnsSTTService"
    ],
    "deepgram_stt": ["from pipecat.services.deepgram.stt import DeepgramSTTService"],
    "deepgram_flux_stt": ["from pipecat.services.deepgram.flux.stt import DeepgramFluxSTTService"],
    "deepgram_flux_sagemaker_stt": [
        "from pipecat.services.deepgram.flux.sagemaker.stt import DeepgramFluxSageMakerSTTService"
    ],
    "deepgram_sagemaker_stt": [
        "from pipecat.services.deepgram.sagemaker.stt import DeepgramSageMakerSTTService"
    ],
    "elevenlabs_stt": ["from pipecat.services.elevenlabs.stt import ElevenLabsSTTService"],
    "elevenlabs_realtime_stt": [
        "from pipecat.services.elevenlabs.stt import ElevenLabsRealtimeSTTService"
    ],
    "fal_stt": ["from pipecat.services.fal.stt import FalSTTService"],
    "gladia_stt": ["from pipecat.services.gladia.stt import GladiaSTTService"],
    "google_stt": ["from pipecat.services.google.stt import GoogleSTTService"],
    "gradium_stt": ["from pipecat.services.gradium.stt import GradiumSTTService"],
    "groq_stt": ["from pipecat.services.groq.stt import GroqSTTService"],
    "mistral_stt": ["from pipecat.services.mistral.stt import MistralSTTService"],
    "nvidia_stt": ["from pipecat.services.nvidia.stt import NvidiaSTTService"],
    "nvidia_sagemaker_stt": [
        "from pipecat.services.nvidia.sagemaker.stt import NvidiaSageMakerSTTService"
    ],
    "openai_stt": ["from pipecat.services.openai.stt import OpenAISTTService"],
    "openai_realtime_stt": ["from pipecat.services.openai.stt import OpenAIRealtimeSTTService"],
    "sarvam_stt": ["from pipecat.services.sarvam.stt import SarvamSTTService"],
    "soniox_stt": ["from pipecat.services.soniox.stt import SonioxSTTService"],
    "speechmatics_stt": ["from pipecat.services.speechmatics.stt import SpeechmaticsSTTService"],
    "moonshine_stt": ["from pipecat.services.moonshine.stt import MoonshineSTTService"],
    "whisper_stt": ["from pipecat.services.whisper.stt import WhisperSTTService"],
    "xai_stt": ["from pipecat.services.xai.stt import XAISTTService"],
    # LLM Services
    "anthropic_llm": ["from pipecat.services.anthropic.llm import AnthropicLLMService"],
    "aws_bedrock_llm": ["from pipecat.services.aws.llm import AWSBedrockLLMService"],
    "azure_llm": ["from pipecat.services.azure.llm import AzureLLMService"],
    "cerebras_llm": ["from pipecat.services.cerebras.llm import CerebrasLLMService"],
    "deepseek_llm": ["from pipecat.services.deepseek.llm import DeepSeekLLMService"],
    "fireworks_llm": ["from pipecat.services.fireworks.llm import FireworksLLMService"],
    "google_gemini_llm": ["from pipecat.services.google.llm import GoogleLLMService"],
    "google_vertex_llm": ["from pipecat.services.google.vertex.llm import GoogleVertexLLMService"],
    "xai_llm": ["from pipecat.services.xai.llm import GrokLLMService"],
    "groq_llm": ["from pipecat.services.groq.llm import GroqLLMService"],
    "inception_llm": ["from pipecat.services.inception.llm import InceptionLLMService"],
    "mistral_llm": ["from pipecat.services.mistral.llm import MistralLLMService"],
    "novita_llm": ["from pipecat.services.novita.llm import NovitaLLMService"],
    "nvidia_llm": ["from pipecat.services.nvidia.llm import NvidiaLLMService"],
    "ollama_llm": ["from pipecat.services.ollama.llm import OLLamaLLMService"],
    "openai_llm": ["from pipecat.services.openai.llm import OpenAILLMService"],
    "openai_responses_llm": [
        "from pipecat.services.openai.responses.llm import OpenAIResponsesLLMService"
    ],
    "openrouter_llm": ["from pipecat.services.openrouter.llm import OpenRouterLLMService"],
    "perplexity_llm": ["from pipecat.services.perplexity.llm import PerplexityLLMService"],
    "qwen_llm": ["from pipecat.services.qwen.llm import QwenLLMService"],
    "sambanova_llm": ["from pipecat.services.sambanova.llm import SambaNovaLLMService"],
    "sarvam_llm": ["from pipecat.services.sarvam.llm import SarvamLLMService"],
    "together_llm": ["from pipecat.services.together.llm import TogetherLLMService"],
    # TTS Services
    "asyncai_tts": ["from pipecat.services.asyncai.tts import AsyncAITTSService"],
    "aws_polly_tts": ["from pipecat.services.aws.tts import AWSPollyTTSService"],
    "azure_tts": ["from pipecat.services.azure.tts import AzureTTSService"],
    "camb_tts": ["from pipecat.services.camb.tts import CambTTSService"],
    "cartesia_tts": ["from pipecat.services.cartesia.tts import CartesiaTTSService"],
    "deepgram_tts": ["from pipecat.services.deepgram.tts import DeepgramTTSService"],
    "deepgram_sagemaker_tts": [
        "from pipecat.services.deepgram.sagemaker.tts import DeepgramSageMakerTTSService"
    ],
    "elevenlabs_tts": ["from pipecat.services.elevenlabs.tts import ElevenLabsTTSService"],
    "fish_tts": ["from pipecat.services.fish.tts import FishAudioTTSService"],
    "gemini_tts": ["from pipecat.services.google.tts import GeminiTTSService"],
    "google_tts": ["from pipecat.services.google.tts import GoogleTTSService"],
    "gradium_tts": ["from pipecat.services.gradium.tts import GradiumTTSService"],
    "groq_tts": ["from pipecat.services.groq.tts import GroqTTSService"],
    "hume_tts": ["from pipecat.services.hume.tts import HumeTTSService"],
    "inworld_tts": ["from pipecat.services.inworld.tts import InworldTTSService"],
    "kokoro_tts": ["from pipecat.services.kokoro.tts import KokoroTTSService"],
    "lmnt_tts": ["from pipecat.services.lmnt.tts import LmntTTSService"],
    "minimax_tts": ["from pipecat.services.minimax.tts import MiniMaxHttpTTSService"],
    "mistral_tts": ["from pipecat.services.mistral.tts import MistralTTSService"],
    "neuphonic_tts": ["from pipecat.services.neuphonic.tts import NeuphonicTTSService"],
    "nvidia_tts": ["from pipecat.services.nvidia.tts import NvidiaTTSService"],
    "nvidia_sagemaker_tts": [
        "from pipecat.services.nvidia.sagemaker.tts import NvidiaSageMakerTTSService"
    ],
    "openai_tts": ["from pipecat.services.openai.tts import OpenAITTSService"],
    "piper_tts": ["from pipecat.services.piper.tts import PiperTTSService"],
    "resemble_tts": ["from pipecat.services.resembleai.tts import ResembleAITTSService"],
    "rime_tts": ["from pipecat.services.rime.tts import RimeTTSService"],
    "sarvam_tts": ["from pipecat.services.sarvam.tts import SarvamTTSService"],
    "smallest_tts": ["from pipecat.services.smallest.tts import SmallestTTSService"],
    "soniox_tts": ["from pipecat.services.soniox.tts import SonioxTTSService"],
    "xai_tts": ["from pipecat.services.xai.tts import XAITTSService"],
    "xtts_tts": ["from pipecat.services.xtts.tts import XTTSService"],
    # Realtime Services
    "aws_nova_realtime": ["from pipecat.services.aws.nova_sonic.llm import AWSNovaSonicLLMService"],
    "azure_realtime": [
        "from pipecat.services.azure.realtime.llm import AzureRealtimeLLMService",
        "from pipecat.services.openai.realtime.events import SessionProperties, InputAudioTranscription",
    ],
    "gemini_live_realtime": [
        "from pipecat.services.google.gemini_live.llm import GeminiLiveLLMService"
    ],
    "gemini_vertex_live_realtime": [
        "from pipecat.services.google.gemini_live.vertex.llm import GeminiLiveVertexLLMService"
    ],
    "xai_realtime": [
        "from pipecat.services.xai.realtime.events import SessionProperties",
        "from pipecat.services.xai.realtime.llm import GrokRealtimeLLMService",
    ],
    "openai_realtime": [
        "from pipecat.services.openai.realtime.events import SessionProperties, AudioConfiguration, AudioInput, InputAudioTranscription, SemanticTurnDetection, InputAudioNoiseReduction",
        "from pipecat.services.openai.realtime.llm import OpenAIRealtimeLLMService",
    ],
    "ultravox": [
        "from pipecat.services.ultravox.llm import UltravoxRealtimeLLMService, OneShotInputParams",
        "import datetime",
    ],
    # Video Services
    "heygen_video": [
        "from pipecat.services.heygen.video import HeyGenVideoService",
        "from pipecat.services.heygen.api_liveavatar import LiveAvatarNewSessionRequest",
        "from pipecat.services.heygen.client import ServiceType",
    ],
    "tavus_video": ["from pipecat.services.tavus.video import TavusVideoService"],
    "simli_video": ["from pipecat.services.simli.video import SimliVideoService"],
}

# Additional imports for features (generated from FEATURE_DEFINITIONS)
FEATURE_IMPORTS = {
    "recording": [
        "import aiofiles",
        "import datetime",
        "import io",
        "from pipecat.processors.audio.audio_buffer_processor import AudioBufferProcessor",
        "import wave",
    ],
    "transcription": [
        "from pipecat.processors.aggregators.llm_response_universal import AssistantTurnStoppedMessage, UserTurnStoppedMessage"
    ],
    "vad": ["from pipecat.audio.vad.silero import SileroVADAnalyzer"],
    "pipeline": [
        "from pipecat.pipeline.pipeline import Pipeline",
        "from pipecat.pipeline.worker import PipelineParams, PipelineWorker",
        "from pipecat.workers.runner import WorkerRunner",
    ],
    "context": [
        "from pipecat.processors.aggregators.llm_context import LLMContext",
        "from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair, LLMUserAggregatorParams",
    ],
    "runner": [
        "from dotenv import load_dotenv",
        "from pipecat.runner.types import RunnerArguments",
        "from pipecat.transports.base_transport import BaseTransport",
    ],
    "llm_run_frame": ["from pipecat.frames.frames import LLMRunFrame"],
    "observability": ["from pipecat_whisker import WhiskerObserver"],
    "external_turn_strategies": [
        "from pipecat.turns.user_turn_strategies import ExternalUserTurnStrategies"
    ],
    "create_transport": ["from pipecat.runner.utils import create_transport"],
    "eval": ["from pipecat.evals.transport import EvalTransportParams"],
}

# Base imports always included in generated bot files
BASE_IMPORTS = [
    "import os",
    "from loguru import logger",
]
