#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot_dev.py
"""


import asyncio
import json
import os
import threading  # PeriodicSmartTurnAnalyzer
import time
import uuid
from concurrent.futures import Future as ConcurrentFuture  # PeriodicSmartTurnAnalyzer
from datetime import datetime

from pipecat.pipeline.runner import PipelineRunner
from pipecat.transports.base_transport import BaseTransport
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.frames.frames import (
    BotStartedSpeakingFrame,
    BotStoppedSpeakingFrame,
    LLMFullResponseEndFrame,
    LLMFullResponseStartFrame,
    LLMRunFrame,
    LLMTextFrame,
    MetricsFrame,
    TextFrame,
    TranscriptionFrame,
    UserStoppedSpeakingFrame,
    VADUserStartedSpeakingFrame,
    VADUserStoppedSpeakingFrame,
)
from pipecat.services.deepgram.stt import DeepgramSTTService
from loguru import logger
from pipecat.metrics.metrics import TurnMetricsData
from pipecat.observers.base_observer import BaseObserver, FramePushed
from pipecat.processors.frame_processor import FrameDirection
from pipecat.runner.types import SmallWebRTCRunnerArguments
from pipecat.pipeline.pipeline import Pipeline
from dotenv import load_dotenv
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair, LLMUserAggregatorParams
from pipecat.runner.types import RunnerArguments
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.base_transport import TransportParams
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.turns.user_turn_strategies import UserTurnStrategies
from pipecat.turns.user_stop.turn_analyzer_user_turn_stop_strategy import TurnAnalyzerUserTurnStopStrategy
from pipecat.audio.turn.smart_turn.local_smart_turn_v3 import LocalSmartTurnAnalyzerV3  # PeriodicSmartTurnAnalyzer
from pipecat.audio.turn.base_turn_analyzer import EndOfTurnState  # PeriodicSmartTurnAnalyzer

load_dotenv(override=True)

# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------
# Set ENABLE_LOGGING to False to suppress all conversation logging.
ENABLE_LOGGING = True
# Directory for per-session JSONL log files (created automatically if missing).
LOG_DIR = os.path.join(os.path.dirname(__file__), "logs")


# ---------------------------------------------------------------------------
# Periodic smart-turn analyzer (disabled)
# ---------------------------------------------------------------------------

class PeriodicSmartTurnAnalyzer(LocalSmartTurnAnalyzerV3):
    """LocalSmartTurnAnalyzerV3 that also runs inference at a fixed interval
    during active speech, not only at VAD-stop.

    Intermediate results are stored in a thread-safe list and drained by
    ConversationLogObserver, providing higher-resolution turn-probability logs
    without requiring an external streaming SDK.
    """

    def __init__(self, *, inference_interval_ms: int = 50, **kwargs):
        """Initialize the periodic smart-turn analyzer.

        Args:
            inference_interval_ms: Minimum gap in milliseconds between
                periodic inference runs during active speech. Defaults to 200.
            **kwargs: Additional arguments passed to LocalSmartTurnAnalyzerV3.
        """
        super().__init__(**kwargs)
        self._inference_interval_ms = inference_interval_ms
        self._last_periodic_time: float = 0.0
        self._pending_metrics: list[TurnMetricsData] = []
        self._pending_lock = threading.Lock()

    def append_audio(self, buffer: bytes, is_speech: bool) -> EndOfTurnState:
        state = super().append_audio(buffer, is_speech)
        now = time.time()
        if (
            is_speech
            and self._speech_triggered
            and (now - self._last_periodic_time) >= self._inference_interval_ms / 1000
        ):
            self._last_periodic_time = now
            # Snapshot the buffer so the background thread reads stable data
            buffer_snapshot = list(self._audio_buffer)
            future: ConcurrentFuture = self._executor.submit(
                self._process_speech_segment, buffer_snapshot
            )
            future.add_done_callback(self._on_periodic_done)
        return state

    def _on_periodic_done(self, future: ConcurrentFuture):
        try:
            _, metrics = future.result()
            if metrics is not None:
                with self._pending_lock:
                    self._pending_metrics.append(metrics)
        except Exception as e:
            logger.debug(f"PeriodicSmartTurnAnalyzer: inference error: {e}")

    def drain_metrics(self) -> list[TurnMetricsData]:
        """Pop and return all accumulated periodic metrics (thread-safe)."""
        with self._pending_lock:
            result = list(self._pending_metrics)
            self._pending_metrics.clear()
            return result

    def clear(self):
        super().clear()
        with self._pending_lock:
            self._pending_metrics.clear()
        self._last_periodic_time = 0.0


# ---------------------------------------------------------------------------
# Conversation logger
# ---------------------------------------------------------------------------

class ConversationLogObserver(BaseObserver):
    """Observer that writes a per-session JSONL event log for later analysis.

    Three event streams are captured:
    - ``bot_speech_changed``  — binary, emitted on every start/stop
    - ``bot_state_changed``   — coarse 5-state machine (idle, listening,
                                user_speaking, processing, speaking)
    - ``turn_probability``    — smart-turn model output, every inference
                                while the user is VAD-active

    Each line is a JSON object: ``{"ts_ns": <int>, "event": "<name>", ...}``
    where ``ts_ns`` is the pipeline-clock nanosecond offset from session start.
    The ``pipeline_started`` event additionally carries ``wall_clock_unix_ns``
    so timestamps can be anchored to real time during analysis.
    """

    def __init__(self, turn_analyzer: "PeriodicSmartTurnAnalyzer | None" = None):
        super().__init__()
        self._turn_analyzer = turn_analyzer  # PeriodicSmartTurnAnalyzer
        self._polling_task: asyncio.Task | None = None  # PeriodicSmartTurnAnalyzer
        self._session_id = uuid.uuid4().hex[:8]
        os.makedirs(LOG_DIR, exist_ok=True)
        ts_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"session_{ts_str}_{self._session_id}.jsonl"
        self._filepath = os.path.join(LOG_DIR, filename)
        # Line-buffered so each event is flushed immediately.
        self._file = open(self._filepath, "w", buffering=1, encoding="utf-8")
        self._bot_state: str = "idle"
        self._vad_user_speaking: bool = False
        # Transcript accumulation
        self._in_user_turn: bool = False  # True from first VAD start until UserStoppedSpeakingFrame
        self._user_turn_start_ts: int = 0
        self._user_transcript_parts: list[str] = []
        self._bot_turn_start_ts: int = 0
        self._bot_transcript_parts: list[str] = []
        self._llm_response_active: bool = False
        # Deduplicate: each frame is observed once per pipeline segment boundary.
        # Track seen frame object ids to process each frame exactly once.
        self._seen_frame_ids: set[int] = set()
        self._wall_clock_start_ns: int = 0  # set in on_pipeline_started for periodic ts
        logger.info(f"ConversationLogObserver: logging to {self._filepath}")

    # ------------------------------------------------------------------
    # BaseObserver interface
    # ------------------------------------------------------------------

    async def on_pipeline_started(self):
        """Log session anchor: ties pipeline ts_ns offsets to wall time."""
        self._wall_clock_start_ns = time.time_ns()
        self._log("pipeline_started", 0, wall_clock_unix_ns=self._wall_clock_start_ns, session_id=self._session_id)
        if self._turn_analyzer is not None:  # PeriodicSmartTurnAnalyzer
            self._polling_task = asyncio.create_task(self._poll_periodic_metrics())

    async def _poll_periodic_metrics(self):  # PeriodicSmartTurnAnalyzer
        """Drain PeriodicSmartTurnAnalyzer results and write them to the log."""
        try:
            while True:
                await asyncio.sleep(0.05)  # 20 Hz — well below the 200 ms inference interval
                if not (self._vad_user_speaking or self._in_user_turn):
                    continue
                for m in self._turn_analyzer.drain_metrics():
                    self._log(
                        "turn_probability",
                        time.time_ns() - self._wall_clock_start_ns,
                        probability=m.probability,
                        is_complete=m.is_complete,
                        e2e_ms=m.e2e_processing_time_ms,
                        source="periodic",
                    )
        except asyncio.CancelledError:
            pass

    async def on_push_frame(self, data: FramePushed):
        # Only process downstream frames to avoid double-logging bidirectional
        # system frames such as BotStartedSpeakingFrame.
        if data.direction != FrameDirection.DOWNSTREAM:
            return

        # Each frame passes through once per pipeline segment boundary; skip
        # frames we have already processed to avoid duplicate events/accumulation.
        # Use frame.id (a stable monotonic integer) rather than Python's id()
        # (memory address) which gets reused after GC and causes false skips.
        frame_id = data.frame.id
        if frame_id in self._seen_frame_ids:
            return
        self._seen_frame_ids.add(frame_id)

        ts = data.timestamp
        frame = data.frame

        if isinstance(frame, VADUserStartedSpeakingFrame):
            self._vad_user_speaking = True
            if not self._in_user_turn:
                # First VAD onset for this turn — record start and reset transcript.
                self._in_user_turn = True
                self._user_turn_start_ts = ts
                self._user_transcript_parts = []
            # else: mid-turn VAD re-fire after a pause — keep existing start/transcript
            self._transition_state("user_speaking", ts)

        elif isinstance(frame, VADUserStoppedSpeakingFrame):
            # VAD confirmed silence — note: state stays 'user_speaking' until
            # the turn model releases the turn via UserStoppedSpeakingFrame.
            self._vad_user_speaking = False

        elif isinstance(frame, TranscriptionFrame):
            # Must come before TextFrame — TranscriptionFrame is a TextFrame subclass.
            # Guard: only collect while tracking a turn; late STT results from a
            # finished turn must not contaminate the next one.
            if self._in_user_turn:
                self._user_transcript_parts.append(frame.text)

        elif isinstance(frame, UserStoppedSpeakingFrame):
            text = " ".join(self._user_transcript_parts).strip()
            self._log("user_turn", ts, start_ts_ns=self._user_turn_start_ts, end_ts_ns=ts, text=text)
            self._in_user_turn = False
            self._user_transcript_parts = []  # clear immediately so stale text can't leak
            self._transition_state("processing", ts)

        elif isinstance(frame, LLMFullResponseStartFrame):
            self._bot_transcript_parts = []
            self._llm_response_active = True

        elif isinstance(frame, LLMFullResponseEndFrame):
            self._llm_response_active = False

        elif isinstance(frame, LLMTextFrame):
            if self._llm_response_active:
                self._bot_transcript_parts.append(frame.text)

        elif isinstance(frame, BotStartedSpeakingFrame):
            self._bot_turn_start_ts = ts
            self._transition_state("speaking", ts)
            self._log("bot_speech_changed", ts, active=True)

        elif isinstance(frame, BotStoppedSpeakingFrame):
            text = "".join(self._bot_transcript_parts).strip()
            self._log("bot_turn", ts, start_ts_ns=self._bot_turn_start_ts, end_ts_ns=ts, text=text)
            self._transition_state("listening", ts)
            self._log("bot_speech_changed", ts, active=False)

        elif isinstance(frame, MetricsFrame):
            if self._bot_state == "user_speaking":
                for item in frame.data:
                    if isinstance(item, TurnMetricsData):
                        self._log(
                            "turn_probability",
                            ts,
                            probability=item.probability,
                            is_complete=item.is_complete,
                            e2e_ms=item.e2e_processing_time_ms,
                        )

    async def cleanup(self):
        if self._polling_task is not None:  # PeriodicSmartTurnAnalyzer
            self._polling_task.cancel()
            self._polling_task = None
        await super().cleanup()
        if self._file and not self._file.closed:
            self._file.flush()
            self._file.close()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _transition_state(self, new_state: str, ts_ns: int):
        """Emit a bot_state_changed event only when the state actually changes."""
        if new_state != self._bot_state:
            self._bot_state = new_state
            self._log("bot_state_changed", ts_ns, state=new_state)

    def _log(self, event: str, ts_ns: int, **payload):
        row = {"ts_ns": ts_ns, "event": event, **payload}
        self._file.write(json.dumps(row) + "\n")


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))

    # Text-to-Speech service
    tts = CartesiaTTSService(
            api_key=os.getenv("CARTESIA_API_KEY"),
            settings=CartesiaTTSService.Settings(
                voice=os.getenv("CARTESIA_VOICE_ID", "71a7ad14-091c-4e8e-a314-022ece01c121"),
            ),
        )


    # LLM service
    llm = OpenAILLMService(
            api_key=os.getenv("OPENAI_API_KEY"),
            settings=OpenAILLMService.Settings(
                model=os.getenv("OPENAI_MODEL", "gpt-4.1"),
                system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can't be spoken. Respond to what the user said in a creative, helpful, and brief way.",
            ),
        )



    context = LLMContext()
    periodic_analyzer = PeriodicSmartTurnAnalyzer(inference_interval_ms=200)  # PeriodicSmartTurnAnalyzer
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
            user_turn_strategies=UserTurnStrategies(  # PeriodicSmartTurnAnalyzer
                stop=[TurnAnalyzerUserTurnStopStrategy(turn_analyzer=periodic_analyzer)]
            ),
        ),
    )


    


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        stt,

        user_aggregator,

        llm,

        tts,

        
        transport.output(),

        
        assistant_aggregator,

    ])


    observers = []
    if ENABLE_LOGGING:
        observers.append(ConversationLogObserver(turn_analyzer=periodic_analyzer))

    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=observers,
    )

    @task.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message({"role": "user", "content": "Please introduce yourself."})
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()




    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()