#!/usr/bin/env python3
#
# Copyright (c) 2024-2026, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""Generate the deprecation registry (``scripts/deprecations/deprecations.json``).

AST-parses every ``.. deprecated::`` directive and PEP 702 ``@deprecated``
decorator in the source tree (via ``scripts/deprecations/scan.py``) into a
machine-readable registry committed alongside this generator. Downstream tooling
— the pipecat-context-hub ``check_deprecation`` query, IDE plugins, docs — reads
the JSON from a checkout instead of re-parsing the source, so there is one
authoritative producer. It is build tooling output, not shipped runtime data.

Refuses to write if the audit's validators find any malformed marker, so the
registry is never built from bad input. Run::

    uv run python scripts/deprecations/generate.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from deprecations import scan as dscan  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src" / "pipecat"
REGISTRY_PATH = Path(__file__).resolve().parent / "deprecations.json"
SCHEMA_VERSION = 1


def build_registry(src_root: Path = SRC_ROOT) -> dict:
    """Build the registry document. Raises ``ValueError`` on validation failures."""
    scan = dscan.scan_source(src_root)
    violations = dscan.all_violations(scan)
    if violations:
        raise ValueError(
            "Refusing to build the deprecation registry — fix these markers first:\n"
            + "\n".join(f"  {v}" for v in violations)
        )
    return {
        "_comment": (
            "AUTO-GENERATED by scripts/deprecations/generate.py from the source tree's "
            ".. deprecated:: directives and @deprecated decorators. DO NOT EDIT BY HAND."
        ),
        "schema_version": SCHEMA_VERSION,
        "deprecations": dscan.build_records(scan),
    }


def render(registry: dict) -> str:
    """Deterministic JSON text (stable across runs for clean git diffs)."""
    return json.dumps(registry, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def main() -> int:
    try:
        registry = build_registry()
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 1

    REGISTRY_PATH.write_text(render(registry), encoding="utf-8")

    records = registry["deprecations"]
    print(f"Wrote {len(records)} deprecation records to {REGISTRY_PATH.relative_to(REPO_ROOT)}")

    # Non-gating visibility: deprecation warns the registry does not capture
    # (shared warning helpers, behavior deprecations with no owning symbol).
    uncaptured = dscan.undocumented_warn_sites(dscan.scan_source(SRC_ROOT))
    if uncaptured:
        print(f"\n{len(uncaptured)} deprecation warning(s) not captured (no directive):")
        for key in uncaptured:
            print(f"  {key}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
